export const themeTokenNames = [
  '--vui-color-bg',
  '--vui-color-surface',
  '--vui-color-surface-sunken',
  '--vui-color-surface-raised',
  '--vui-color-surface-hover',
  '--vui-color-text',
  '--vui-color-text-muted',
  '--vui-color-text-strong',
  '--vui-color-accent',
  '--vui-color-accent-soft',
  '--vui-color-accent-strong',
  '--vui-color-line',
  '--vui-color-line-strong',
  '--vui-color-input-bg',
  '--vui-color-input-bg-focus',
  '--vui-color-btn-primary-hover',
];

export const themePresets = {
  vellum: {
    label: 'Vellum',
    description: 'The production palette.',
    light: {},
    dark: {},
  },
  moss: {
    label: 'Moss',
    description: 'A quieter library-green direction.',
    light: {
      '--vui-color-bg': '#f2f0e7',
      '--vui-color-surface': '#e7e7d9',
      '--vui-color-surface-sunken': '#dcddcf',
      '--vui-color-surface-raised': '#fbfaf4',
      '--vui-color-surface-hover': '#e1e3d6',
      '--vui-color-text': '#29312b',
      '--vui-color-text-muted': '#536058',
      '--vui-color-text-strong': '#172019',
      '--vui-color-accent': '#4c6d55',
      '--vui-color-accent-soft': '#dfe9df',
      '--vui-color-accent-strong': '#304a37',
      '--vui-color-line': 'rgba(43, 63, 48, 0.18)',
      '--vui-color-line-strong': '#78857b',
      '--vui-color-input-bg': '#fffef9',
      '--vui-color-input-bg-focus': '#ffffff',
      '--vui-color-btn-primary-hover': '#3f5e48',
    },
    dark: {
      '--vui-color-bg': '#171c18',
      '--vui-color-surface': '#202721',
      '--vui-color-surface-sunken': '#121713',
      '--vui-color-surface-raised': '#29312a',
      '--vui-color-surface-hover': '#323c34',
      '--vui-color-text': '#e8eee8',
      '--vui-color-text-muted': '#a8b3aa',
      '--vui-color-text-strong': '#f9fff9',
      '--vui-color-accent': '#9fc3a6',
      '--vui-color-accent-soft': '#2c4030',
      '--vui-color-accent-strong': '#c5dec9',
      '--vui-color-line': 'rgba(220, 239, 224, 0.15)',
      '--vui-color-line-strong': '#657369',
      '--vui-color-input-bg': '#29312a',
      '--vui-color-input-bg-focus': '#313a32',
      '--vui-color-btn-primary-hover': '#add0b4',
    },
  },
  blueprint: {
    label: 'Blueprint',
    description: 'A cooler, more technical direction.',
    light: {
      '--vui-color-bg': '#f1f4f7',
      '--vui-color-surface': '#e5ebf0',
      '--vui-color-surface-sunken': '#d9e2e9',
      '--vui-color-surface-raised': '#fbfdff',
      '--vui-color-surface-hover': '#dfe7ee',
      '--vui-color-text': '#27323c',
      '--vui-color-text-muted': '#53616d',
      '--vui-color-text-strong': '#14212c',
      '--vui-color-accent': '#416987',
      '--vui-color-accent-soft': '#dceaf3',
      '--vui-color-accent-strong': '#284b67',
      '--vui-color-line': 'rgba(36, 64, 84, 0.18)',
      '--vui-color-line-strong': '#718492',
      '--vui-color-input-bg': '#ffffff',
      '--vui-color-input-bg-focus': '#ffffff',
      '--vui-color-btn-primary-hover': '#355b78',
    },
    dark: {
      '--vui-color-bg': '#151b21',
      '--vui-color-surface': '#1d252d',
      '--vui-color-surface-sunken': '#10161b',
      '--vui-color-surface-raised': '#26313a',
      '--vui-color-surface-hover': '#303c46',
      '--vui-color-text': '#e6edf3',
      '--vui-color-text-muted': '#a6b2bc',
      '--vui-color-text-strong': '#f8fbff',
      '--vui-color-accent': '#91bddb',
      '--vui-color-accent-soft': '#273d4d',
      '--vui-color-accent-strong': '#c4dfef',
      '--vui-color-line': 'rgba(220, 235, 246, 0.15)',
      '--vui-color-line-strong': '#627786',
      '--vui-color-input-bg': '#26313a',
      '--vui-color-input-bg-focus': '#2e3a44',
      '--vui-color-btn-primary-hover': '#a3cbe5',
    },
  },
  graphite: {
    label: 'Graphite',
    description: 'A nearly monochrome direction that makes hierarchy do the work.',
    light: {
      '--vui-color-bg': '#f4f3f1',
      '--vui-color-surface': '#e9e7e4',
      '--vui-color-surface-sunken': '#dedbd7',
      '--vui-color-surface-raised': '#fdfcfb',
      '--vui-color-surface-hover': '#e3e0dc',
      '--vui-color-text': '#2b2927',
      '--vui-color-text-muted': '#5b5753',
      '--vui-color-text-strong': '#181716',
      '--vui-color-accent': '#4e4b48',
      '--vui-color-accent-soft': '#e2dfdc',
      '--vui-color-accent-strong': '#2e2c2a',
      '--vui-color-line': 'rgba(40, 37, 34, 0.17)',
      '--vui-color-line-strong': '#817c77',
      '--vui-color-input-bg': '#ffffff',
      '--vui-color-input-bg-focus': '#ffffff',
      '--vui-color-btn-primary-hover': '#3e3b38',
    },
    dark: {
      '--vui-color-bg': '#191817',
      '--vui-color-surface': '#22211f',
      '--vui-color-surface-sunken': '#131211',
      '--vui-color-surface-raised': '#2c2a28',
      '--vui-color-surface-hover': '#35322f',
      '--vui-color-text': '#ebe8e4',
      '--vui-color-text-muted': '#aaa5a0',
      '--vui-color-text-strong': '#fffdf9',
      '--vui-color-accent': '#c5c0bb',
      '--vui-color-accent-soft': '#3a3734',
      '--vui-color-accent-strong': '#ece8e3',
      '--vui-color-line': 'rgba(238, 233, 227, 0.14)',
      '--vui-color-line-strong': '#716c67',
      '--vui-color-input-bg': '#2c2a28',
      '--vui-color-input-bg-focus': '#34312f',
      '--vui-color-btn-primary-hover': '#d2cdc7',
    },
  },
};

export function applyThemePreset(root, presetName = 'vellum', mode = 'light') {
  for (const token of themeTokenNames) root.style.removeProperty(token);
  const preset = themePresets[presetName] || themePresets.vellum;
  for (const [token, value] of Object.entries(preset[mode] || preset.light || {})) {
    root.style.setProperty(token, value);
  }
}
